[+ AutoGen5 template h adf +] 
[+ CASE (suffix) +]
[+ ==  h  +]
#pragma once 
#define MAXARGS [+ nadf[0].maxarg +]
[+dtypestruct+]
#define DATATYPE [+ dtype +]
[+ additionaldefines +]
[+ ==  adf  +]
#pragma once 
#define MAXARGS [+ yadf[0].maxarg+]
[+dtypestruct+]
#define DATATYPE [+ dtype +]
[+ additionaldefines +]
[+ ESAC +]
