CREATE TABLE sttlong(
  "RowNum" INTEGER,
  "ProblemNum" INTEGER,
  "Kernel" INTEGER,
  "IndRunNum" INTEGER,
  "wADF" char(1),
  "ADF" char(1),
  "Types" char(1),
  "Constraints" char(1),
  "acgpwhat" INTEGER,
  "MaxTreeDepth" INTEGER,
  "GenNum" INTEGER,
  "SubPopNum" INTEGER,
  "MeanStdFitnessOfGen" REAL,
  "StdFitnessBestOfGenInd" REAL,
  "StdFitnessWorstOfGenInd" REAL,
  "MeanTreeSizeOfGen" REAL,
  "MeanTreeDepthOfGen" REAL,
  "TreeSizeBestOfGenInd" INTEGER,
  "TreeDepthBestOfGenInd" INTEGER,
  "TreeSizeWorstOfGenInd" INTEGER,
  "TreeDepthWorstOfGenInd" REAL,
  "MeanStdFitnessOfRun" REAL,
  "StdFitnessBestOfRunInd" REAL,
  "StdFitnessWorstOfRunInd" REAL,
  "MeanTreeSizeOfRun" REAL,
  "MeanTreeDepthOfRun" REAL,
  "TreeSizeBestOfRunInd" INTEGER,
  "TreeDepthBestOfRunInd" INTEGER,
  "TreeSizeWorstOfRunInd" INTEGER,
  "TreeDepthWorstOfRunInd" INTEGER
);

