/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION harmonic
 */
extern_c double C_harmonic(double L1_n)
{
  TRACE_PUSH("C_harmonic");
  MM_ENTER;
  {
    double L_Tmp0;
    {
      double L2_1_z;
      double L2_2_i;
      L2_1_z = 0;
      L2_2_i = 0;
      L_Tmp0 = 0;
      /* While loop */

      {
        MM_ENTER;
        goto L_1;

L_0:

        {
          L2_2_i = (L2_2_i+1);
          L2_1_z = (L2_1_z+(((double)1)/((double)L2_2_i)));
          L_Tmp0 = L2_1_z;
        }
        /* While loop test*/

L_1:

        {
          MM_EXIT;

          if ((L2_2_i<L1_n)) goto L_0;

        }
      }
    }
    TRACE_POP("C_harmonic");
    MM_EXIT;
    return L_Tmp0;
  }
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB harmonic
 */
DH(X_harmonic)
{
  dharg ret;
  ret.dh_double =  C_harmonic(a[1].dh_double);
  return ret;
}

/*
 * DHDOC harmonic
 */
DHDOC(K_harmonic_Rfc8fe739,X_harmonic,"C_harmonic",0,0) =
{
  DH_FUNC(1),
  DH_DOUBLE,
  DH_RETURN,
  DH_DOUBLE,
  DH_END_FUNC,
  DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_harmonic(void)
{
  dh_define("harmonic", &K_harmonic_Rfc8fe739);
}

int majver_harmonic = 50;
int minver_harmonic = 00;


#endif

