#!/bin/bash 
make -j -C $PWD/orig_ywadf_nadf_ntypes_ncons_nwhatn clean
make -j -C $PWD/orig_ywadf_yadf_ntypes_ncons_nwhatn clean
make -j -C $PWD/cgp2p1_nwadf_nadf_ntypes_ncons_nwhatn clean
make -j -C $PWD/cgp2p1_nwadf_nadf_ntypes_ycons_nwhatn clean
make -j -C $PWD/cgp2p1_nwadf_nadf_ytypes_ncons_nwhatn clean
make -j -C $PWD/cgp2p1_nwadf_nadf_ytypes_ycons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_nadf_ntypes_ncons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_nadf_ntypes_ycons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_nadf_ytypes_ncons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_nadf_ytypes_ycons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_yadf_ntypes_ncons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_yadf_ntypes_ycons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_yadf_ytypes_ncons_nwhatn clean
make -j -C $PWD/cgpf2p1_ywadf_yadf_ytypes_ycons_nwhatn clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ncons_ywhat0 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ncons_ywhat1 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ncons_ywhat2 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ncons_ywhat3 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ycons_ywhat0 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ycons_ywhat1 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ycons_ywhat2 clean
make -j -C $PWD/acgp1p1p2_nwadf_nadf_ntypes_ycons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ncons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ycons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ncons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ycons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ncons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ycons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ncons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ycons_ywhat0 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ncons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ycons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ncons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ycons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ncons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ycons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ncons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ycons_ywhat1 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ncons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ycons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ncons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ycons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ncons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ycons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ncons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ycons_ywhat2 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ncons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ntypes_ycons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ncons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ntypes_ycons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ncons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_nadf_ytypes_ycons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ncons_ywhat3 clean
make -j -C $PWD/acgpf2p1_ywadf_yadf_ytypes_ycons_ywhat3 clean
find . -name "gp" -delete
