#!/bin/sh
./gp -p random_seed=1  -p max_generations=50 -p pop_size=$1 -p acgp.what=2 -p max_depth=7 -p app.use_ercs=0 -p app.save_pop=1 -p output.basename=./tmp_w2/reg_rs1 -f input_w2.file < acgp1p1p2_simple_trig_no_adf_qt.txt 


